# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Order has been created'), ('processing', 'Payment is processing'), ('paid', 'Payment is verified'), ('packaged', 'We are getting your package together'), ('delivered', 'Your package is out for delivery'), ('received', 'Your package has made it to its end location, enjoy!'), ('refunded_processing', 'We are processing your order for a refund'), ('cancelled', 'Your order has been successfully cancelled')], default='created', max_length=120),
        ),
    ]
